### PR TITLE
Major documentation improvement

### PR DESCRIPTION
**Pull request by donmanguno**

### CODE REVIEW

**Comment by EdenKupe** [comment]
@miki2826 lots of improvements here. Can you please review?

**Comment by miki2826** [comment]
@donmanguno Mark, there are conflicts, please resolve first.

**Review by miki2826 — APPROVED** [review]

**Comment by miki2826** [comment]
@donmanguno waiting for you to resolve the conflict before i'm able to merge.

**Comment by donmanguno** [comment]
@miki2826 fixed

**Pull request merged**
